name: Renovate

on:
  schedule:
    - cron: "0 4 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    uses: canonical/sdkcraft-actions/.github/workflows/renovate.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
